name: Feature Request
description: Submit a proposal/request for a new feature
labels: ["feature"]
projects: [""]
body:
  - type: markdown
    attributes:
      value: |
        A clear and concise description of the feature proposal
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please outline the motivation for the proposal.
      placeholder: "Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too"
    validations:
      required: true
  - type: textarea
    id: pitch
    attributes:
      label: Pitch
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered, if any.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
